title: Anchora Trusted I.T. Solutions
creator: Canary Print & Design
email: email@example.com
description: >-
  Anchora provides comprehensive technology services to businesses from Nanaimo and across Vancouver Island. Through our partnerships and your help, Anchora delivers and deploys complete in-house, hybrid, and cloud network solutions.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anchora.ca" # the base hostname & protocol for your site, e.g. http://example.com
incremental: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - hyde-page-css
  - hyde-page-js
  - hyde-decap

hyde_page_css:
  keep_files: true
  dev_mode: true

hyde_page_js:
  keep_files: true
  dev_mode: true

hyde_decap:
  keep_files: false
  enabled: true
  backend:
    name: github
    repo: gregdaynes/anchora.ca # github path to repo
    site_domain: anchora.ca # site name
    branch: main # Branch to update (optional; defaults to master)
  local_backend: true
  publish_mode: editorial_workflow
  media_folder: "/assets/images" # Media files will be stored in the repo under images/uploads
  public_folder: "/assets/images" # The src attribute for uploaded media will begin with /images/uploads
  collections:
    - label: Data
      name: data
      files:
        - label: Sections
          name: sections
          file: _data/sections.yml
          fields:
            - label: Data
              name: data
              widget: list
              allow_add: true
              collapsed: true
              summary: '{{fields.heading}}'
              fields:
              - label: Heading
                name: heading
                widget: string
                required: false
              - label: Image
                name: image
                widget: image
              - label: Code
                name: code
                widget: code
                required: false
              - label: Content
                name: content
                widget: markdown
                required: false
        - label: Contact
          name: contact
          file: _data/contact.yml
          fields:
            - label: Heading
              name: heading
              widget: string
              required: false
            - label: Content
              name: content
              widget: markdown
